name: Temp
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: Bistutu/FluentRead
          ref: 06c1f02c553abb93ed57d6cf9da87844d9a9b11a
          fetch-depth: 1
      - name: Build
        shell: bash
        run: |
          npm install -g wxt pnpm
          pnpm install
          wxt build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: .output/*
          include-hidden-files: true
